import type { Metadata } from 'next'
import { Inter,Manrope } from 'next/font/google'
// import './globals.css'


const inter = Inter({ subsets: ['latin'] })
const manrope =Manrope ({  
  weight: ['400', '600','700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',})

export const metadata: Metadata = {
  title: 'AR SHAKIR',
  description: 'Generated by AR SHAKIR',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
